### ISSUE TITLE
I cant execute any sbt version after install using sbtenv

### ISSUE THREAD

**Issue by ppadialitrs** [sbtenv/sbtenv#20]
Hi all,

After install on an Ubuntu Linux 14.04 i do the following
`sbtenv install sbt-0.13.9`

How i can use sbt now? if i type sbt command is not working because is not installed and if i go to an SBT project and type sbtenv im getting

`is not installedbt-0.13.9
 ( set by /my/path/my/project/build.properties)`
build.properties file contains:

``` sbt.version=0.13.9```

What im doing wrong?

thanks in advance
```

**Comment by agaro1121** [comment]
I am having the same issue as well.
Is there a wiki for this or a solution?

**Comment by dffuller** [comment]
I too am having a similar issue.  There are no files in .sbtenv/shims and `sbtenv which sbt` gives "sbtenv: sbt: command not found'.  This is with either bash or zsh and I have sbt-0.12.2 and sbt-0.13.13 installed.  

I set sbt-0.13.13 as global (this appears to be respected) and in my ~/Projects directory I set sbt-0.12.2 as local and this is not respected (current version from `sbtversion` is shown as `sbt-0.13.13 (set by SBTENV_VERSION environment variable). 

I'm happy to do any troubleshooting if it will help get this issue resolved.  I seem to recall having a similar issue a couple of years ago and managed to find a solution via Google, but no joy this time.

**Comment by dffuller** [comment]
@ppadialitrs , @agaro1121 Did either of you ever find a way to get this working?  Are you both using bash?

**Comment by agaro1121** [comment]
Unfortunately not. I gave up on this for now.

**Comment by alexanderscott** [comment]
looks to me like this is a $PATH or initialization problem.  is `${HOME}/.sbtenv/bin` in your user's `$PATH`?   and is `eval "$(sbtenv init -)"` in your bash profile?

**Comment by dffuller** [comment]
Yes, ${HOME}/.sbtenv/bin is in my path and eval "$(sbtenv init -)" is in my .bashrc.  Both of these are set before the scalaenv analogs and scalaenv is working fine, which seems to rule out missing parens, quotes, etc.

**Comment by j1mr10rd4n** [comment]
This was being caused by the sbt-0.13.13 distribution having a differently-named folder in its tarball.

I've pushed a fix in #27 and asked the maintainers to make a new release in #29.

**Comment by dffuller** [comment]
Thanks for the fix.  For other users, just a heads up - I tried just pulling the new sbtenv and then rehashing, but that didn't work.  I eventually just deleted the `~/.sbtenv` directory and cloned anew to get things working again.  Once I did that, things work as expected again.  It seems now I was too stubborn in not trying other versions of sbt.

If anyone has a better solution, please update the thread.

**Comment by EudyptesCapital** [comment]
I installed sbtenv and execute "git clone" and tried to use `sbt`.
I occured Error of "is not installedbt-0.13.9 ( set by /my/path/my/project/build.properties)"

This cause is character code.  Maybe, You's build.properties character code is DOS(CSRF)?
I resolved by change character code to utf8-unix.

Thanks.
